# Generated by Django 5.1.5 on 2025-05-16 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='appointment_buffer_minutes',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_online_booking',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_patient_portal',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='google_analytics_id',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='max_appointments_per_day',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='patient_registration_open',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='reminder_hours_before',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='require_appointment_approval',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='working_hours_start',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_remember_me',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_expiry_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_min_length',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_require_special',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_require_uppercase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='accent_color',
            field=models.CharField(default='#9b59b6', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='clinic_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='primary_color',
            field=models.CharField(default='#3498db', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='secondary_color',
            field=models.CharField(default='#2ecc71', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='working_days',
            field=models.CharField(blank=True, help_text='Comma-separated list of working days (0-6, Monday to Sunday)', max_length=20),
        ),
    ]
