# Generated by Django 5.1.5 on 2025-05-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_systemsettings_appointment_buffer_minutes_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
